version: '3.9'

services:
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonar
    ports:
      - "9000:9000"
    volumes:
      - ./../volumes/sonarqube/logs:/opt/sonarqube/logs
      - ./../volumes/sonarqube/extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://172.18.0.6:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    networks:
      laboratoriojenkins_lab-snet-01:
        ipv4_address: 172.18.0.5

networks:
  laboratoriojenkins_lab-snet-01:
    external: true
